SUB_DIRS += \
libs/LXSAMD21DMX/src

OBJS += \
libs/LXSAMD21DMX/src/LXSAMD21DMX.o

OBJS_AS_ARGS += \
"libs/LXSAMD21DMX/src/LXSAMD21DMX.o"

DIR_INCLUDES += \
-I"../libs/LXSAMD21DMX/src"

DEPS_AS_ARGS += \
"libs/LXSAMD21DMX/src/LXSAMD21DMX.d"

include Makefile.mk.bak
